---
version: '3.8'
services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=k6
      - POSTGRES_USER=k6
      - POSTGRES_PASSWORD=k6
    volumes: 
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
    driver: local